"""empty message

Revision ID: 58b1d2728a57
Revises: 4810af4a1eda
Create Date: 2020-07-21 13:06:13.354207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b1d2728a57'
down_revision = '4810af4a1eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    ## Handle existing data before adding the 'Completed' column
    op.execute('UPDATE todos SET completed=False WHERE completed IS NULL;')
    # Return the nullable=False condition
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
